name: 'print hello'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
  
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          rubygems: "latest"
          bundler: "latest"
          bundler-cache: true

      - name: Execute ruby command
        run: ruby print-hello.rb